import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'EN' | 'AR';

interface Translations {
  [key: string]: {
    EN: string;
    AR: string;
  };
}

export const translations: Translations = {
  'nav.marketplace': { EN: 'Marketplace', AR: 'السوق' },
  'nav.howItWorks': { EN: 'How It Works', AR: 'كيف تعمل' },
  'nav.useCases': { EN: 'Use Cases', AR: 'حالات الاستخدام' },
  'nav.faq': { EN: 'FAQs', AR: 'الأسئلة الشائعة' },
  'nav.vault': { EN: 'The Vault', AR: 'الخزنة' },
  'nav.assets': { EN: 'Assets', AR: 'الأصول' },
  'nav.lounge': { EN: 'Lounge', AR: 'الردهة' },
  'nav.booking': { EN: 'Booking', AR: 'الحجز' },
  'nav.listAsset': { EN: 'List Asset', AR: 'اعرض أصل' },
  'nav.profile': { EN: 'Profile', AR: 'الملف الشخصي' },
  'nav.settings': { EN: 'Settings', AR: 'الإعدادات' },
  'nav.signout': { EN: 'Sign Out', AR: 'تسجيل الخروج' },
  'nav.signin': { EN: 'Sign In', AR: 'تسجيل الدخول' },
  'nav.helpFaq': { EN: 'Help & FAQ', AR: 'المساعدة والأسئلة الشائعة' },
  'banner.text': { EN: 'Experience Coshare on the go. Download our new app!', AR: 'جرب Coshare أثناء التنقل. قم بتحميل تطبيقنا الجديد!' },
  'banner.cta': { EN: 'Download App', AR: 'تحميل التطبيق' },
  'home.faq.viewAll': { EN: 'View all FAQs', AR: 'عرض جميع الأسئلة الشائعة' },
  'asset.checkout.subtotal': { EN: 'Subtotal', AR: 'المجموع الفرعي' },
  'asset.checkout.discount': { EN: 'Discount', AR: 'الخصم' },
  'asset.checkout.apply': { EN: 'Apply', AR: 'تطبيق' },
  'asset.checkout.promoSuccess': { EN: 'Promo code applied successfully!', AR: 'تم تطبيق رمز الخصم بنجاح!' },
  'asset.checkout.promoInvalid': { EN: 'Invalid promo code', AR: 'رمز خصم غير صالح' },
  'asset.checkout.promoPlaceholder': { EN: 'Add promo or referral code', AR: 'أضف رمز ترويجي أو رمز إحالة' },
  'asset.checkout.signContinue': { EN: 'Sign & Continue', AR: 'توقيع ومتابعة' },
  'asset.checkout.applePay': { EN: 'Pay with Apple Pay', AR: 'الدفع بواسطة Apple Pay' },
  'home.hero.title': { EN: 'Own More. Together.', AR: 'امتلك أكثر. معاً.' },
  'home.hero.subtitle': { EN: 'The AI-powered fractional ownership platform in the UAE.', AR: 'منصة الملكية الجزئية المدعومة بالذكاء الاصطناعي في الإمارات.' },
  'home.hero.start': { EN: 'Start Cosharing', AR: 'ابدأ المشاركة' },
  'home.hero.list': { EN: 'List Your Asset', AR: 'اعرض أصلك' },
  'home.hero.tryApp': { EN: 'Try new App', AR: 'جرب التطبيق الجديد' },
  'home.why.title': { EN: 'Why coshare.', AR: 'لماذا coshare.' },
  'home.why.subtitle': { EN: 'A smarter, RTA-compliant way to access and optimize premium assets in the UAE.', AR: 'طريقة أذكى ومتوافقة مع هيئة الطرق والمواصلات للوصول إلى الأصول الفاخرة وتحسينها في الإمارات.' },
  'home.why.1.title': { EN: 'Smart Ownership', AR: 'ملكية ذكية' },
  'home.why.1.desc': { EN: 'Why pay 100% for an asset you use 15% of the time? Enjoy the full lifestyle for a fraction of the cost.', AR: 'لماذا تدفع 100٪ لأصل تستخدمه 15٪ من الوقت؟ استمتع بأسلوب الحياة الكامل بجزء بسيط من التكلفة.' },
  'home.why.1.badge': { EN: '85% Cost Saving', AR: 'توفير 85٪ في التكلفة' },
  'home.why.2.title': { EN: 'RTA Compliance', AR: 'التوافق مع هيئة الطرق والمواصلات' },
  'home.why.2.desc': { EN: 'Legal title held by a vetted Lead Owner, with all participants registered as authorized Cosharers on the Mulkiya.', AR: 'الملكية القانونية يحتفظ بها مالك رئيسي معتمد، مع تسجيل جميع المشاركين كمشاركين مفوضين في الملكية.' },
  'home.why.2.badge': { EN: 'Legal Framework', AR: 'الإطار القانوني' },
  'home.why.3.title': { EN: 'AI-Powered Agent', AR: 'وكيل مدعوم بالذكاء الاصطناعي' },
  'home.why.3.desc': { EN: 'Your personal co-ownership assistant. Get smart scheduling recommendations, market insights, and instant answers.', AR: 'مساعدك الشخصي للملكية المشتركة. احصل على توصيات جدولة ذكية ورؤى للسوق وإجابات فورية.' },
  'home.why.3.badge': { EN: 'Smart Assistant', AR: 'مساعد ذكي' },
  'home.why.4.title': { EN: 'Hassle-Free', AR: 'بدون عناء' },
  'home.why.4.desc': { EN: 'We handle maintenance, insurance, and storage. You just focus on the experience.', AR: 'نحن نتولى الصيانة والتأمين والتخزين. أنت تركز فقط على التجربة.' },
  'home.why.4.badge': { EN: 'Asset Manager', AR: 'مدير الأصول' },
  'home.why.5.title': { EN: 'Secondary Market', AR: 'السوق الثانوية' },
  'home.why.5.desc': { EN: 'Seamless payments, automated dividend distribution, and our Facilitated Liquidity Protocol for structured secondary market exits.', AR: 'مدفوعات سلسة، وتوزيع آلي للأرباح، وبروتوكول السيولة الميسر الخاص بنا لعمليات التخارج المهيكلة في السوق الثانوية.' },
  'home.why.5.badge': { EN: 'Fintech Solution', AR: 'حلول التكنولوجيا المالية' },
  'home.why.6.title': { EN: 'Vetted Community', AR: 'مجتمع موثوق' },
  'home.why.6.desc': { EN: 'Join a private circle of luxury enthusiasts. Every participant undergoes rigorous vetting.', AR: 'انضم إلى دائرة خاصة من محبي الفخامة. يخضع كل مشارك لعملية تدقيق صارمة.' },
  'home.why.6.badge': { EN: 'Verified Elite', AR: 'نخبة موثقة' },
  'home.featured.title': { EN: 'Featured Assets', AR: 'الأصول المميزة' },
  'home.featured.subtitle': { EN: 'Discover exclusive opportunities.', AR: 'اكتشف فرصاً حصرية.' },
  'home.featured.viewAll': { EN: 'View All Assets', AR: 'عرض جميع الأصول' },
  'home.how.title': { EN: 'How it works', AR: 'كيف تعمل' },
  'home.how.1.title': { EN: '01. List & Invite', AR: '01. اعرض وادعُ' },
  'home.how.1.desc': { EN: 'Post your own asset or discover a new one. Invite your inner circle or find verified co-owners in our secure marketplace.', AR: 'اعرض أصلك الخاص أو اكتشف أصلاً جديداً. ادعُ دائرتك المقربة أو ابحث عن ملاك مشاركين تم التحقق منهم في سوقنا الآمن.' },
  'home.how.2.title': { EN: '02. Stake & Settle', AR: '02. الحصة والتسوية' },
  'home.how.2.desc': { EN: 'Expenses, insurance, and maintenance are automatically split by your stake. Settle costs transparently via the app.', AR: 'يتم تقسيم المصاريف والتأمين والصيانة تلقائياً حسب حصتك. قم بتسوية التكاليف بشفافية عبر التطبيق.' },
  'home.how.3.title': { EN: '03. Smart Scheduling', AR: '03. الجدولة الذكية' },
  'home.how.3.desc': { EN: 'Book your time with ease. Our AI-powered calendar prevents scheduling conflicts automatically, ensuring fair access.', AR: 'احجز وقتك بسهولة. يمنع تقويمنا المدعوم بالذكاء الاصطناعي تضارب المواعيد تلقائياً، مما يضمن وصولاً عادلاً.' },
  'home.how.4.title': { EN: '04. AI Governance', AR: '04. حوكمة الذكاء الاصطناعي' },
  'home.how.4.desc': { EN: 'Experience total peace of mind. From automated maintenance alerts to fair dispute resolution, our AI handles the harmony.', AR: 'استمتع براحة بال تامة. من تنبيهات الصيانة التلقائية إلى حل النزاعات العادل، يتولى الذكاء الاصطناعي الخاص بنا التناغم.' },
  'assets.title': { EN: 'Browse Assets', AR: 'تصفح الأصول' },
  'assets.subtitle': { EN: 'Discover premium fractional ownership opportunities in the UAE.', AR: 'اكتشف فرص الملكية الجزئية المتميزة في الإمارات.' },
  'assets.search': { EN: 'Search assets...', AR: 'ابحث عن الأصول...' },
  'assets.filter.all': { EN: 'All', AR: 'الكل' },
  'assets.filter.cars': { EN: 'Cars', AR: 'سيارات' },
  'assets.filter.motorbikes': { EN: 'Motorbikes', AR: 'دراجات نارية' },
  'assets.filter.yachts': { EN: 'Yachts', AR: 'يخوت' },
  'assets.filter.others': { EN: 'Others', AR: 'أخرى' },
  'assets.empty': { EN: 'No assets found', AR: 'لم يتم العثور على أصول' },
  'assets.empty.desc': { EN: 'Try adjusting your filters to see more results.', AR: 'حاول تعديل الفلاتر لرؤية المزيد من النتائج.' },
  'assets.notify.title': { EN: 'Get Early Access', AR: 'احصل على وصول مبكر' },
  'assets.notify.desc': { EN: 'Be the first to know when we launch our collection.', AR: 'كن أول من يعرف عندما نطلق مجموعتنا.' },
  'assets.notify.email': { EN: 'Email Address', AR: 'البريد الإلكتروني' },
  'assets.notify.joining': { EN: 'Joining...', AR: 'جاري الانضمام...' },
  'assets.notify.join': { EN: 'Join Waitlist', AR: 'انضم لقائمة الانتظار' },
  'assets.notify.success': { EN: "You're on the list!", AR: 'أنت على القائمة!' },
  'assets.notify.spam': { EN: 'No spam. Just exclusive opportunities.', AR: 'لا رسائل مزعجة. فقط فرص حصرية.' },
  'asset.details.about': { EN: 'About this Asset', AR: 'عن هذا الأصل' },
  'asset.details.specs': { EN: 'Specifications', AR: 'المواصفات' },
  'asset.details.legal': { EN: 'Legal & Ownership Structure', AR: 'الهيكل القانوني والملكية' },
  'asset.details.legalDesc': { EN: 'This asset is held in a dedicated, bankruptcy-remote Special Purpose Vehicle (SPV) registered in the Abu Dhabi Global Market (ADGM). By purchasing shares, you are acquiring direct membership interests in this specific LLC.', AR: 'يتم الاحتفاظ بهذا الأصل في شركة ذات غرض خاص (SPV) مخصصة ومستقلة عن الإفلاس مسجلة في سوق أبوظبي العالمي (ADGM). من خلال شراء الحصص، فإنك تحصل على مصالح عضوية مباشرة في هذه الشركة المحدودة المسؤولية.' },
  'asset.details.entityType': { EN: 'Entity Type', AR: 'نوع الكيان' },
  'asset.details.entityValue': { EN: 'ADGM SPV (LLC)', AR: 'شركة ذات غرض خاص في سوق أبوظبي العالمي (LLC)' },
  'asset.details.status': { EN: 'Asset Status', AR: 'حالة الأصل' },
  'asset.details.statusValue': { EN: 'Fully Insured & Secured', AR: 'مؤمن ومؤمن بالكامل' },
  'asset.details.docs': { EN: 'Due Diligence Documents', AR: 'وثائق العناية الواجبة' },
  'asset.details.view': { EN: 'View', AR: 'عرض' },
  'asset.details.benefits': { EN: 'Ownership Benefits', AR: 'فوائد الملكية' },
  'asset.details.usage': { EN: 'Guaranteed Usage Days', AR: 'أيام استخدام مضمونة' },
  'asset.details.usageDesc': { EN: 'Enjoy proportional access to the asset throughout the year based on your share ownership.', AR: 'استمتع بوصول تناسبي للأصل طوال العام بناءً على ملكيتك للحصص.' },
  'asset.details.managed': { EN: 'Fully Managed', AR: 'مدار بالكامل' },
  'asset.details.managedDesc': { EN: 'Maintenance, insurance, and storage are completely handled by the coshare. team.', AR: 'يتم التعامل مع الصيانة والتأمين والتخزين بالكامل من قبل فريق coshare.' },
  'asset.details.simulator': { EN: 'Live Simulator', AR: 'محاكي مباشر' },
  'asset.details.usageLabel': { EN: 'Usage', AR: 'الاستخدام' },
  'asset.details.days': { EN: 'days', AR: 'أيام' },
  'asset.details.yield': { EN: 'Appreciation', AR: 'التقدير' },
  'asset.details.pa': { EN: 'p.a.', AR: 'سنوياً' },
  'asset.details.maint': { EN: 'Maint.', AR: 'الصيانة' },
  'asset.details.equity': { EN: 'Equity', AR: 'الملكية' },
  'asset.details.terms': { EN: 'By proceeding, you agree to our fractional ownership terms and conditions. Capital at risk.', AR: 'بالمتابعة، فإنك توافق على شروط وأحكام الملكية الجزئية الخاصة بنا. رأس المال في خطر.' },
  'asset.checkout.title': { EN: 'Secure Checkout', AR: 'دفع آمن' },
  'asset.checkout.identity': { EN: 'Identity', AR: 'الهوية' },
  'asset.checkout.legal': { EN: 'Legal', AR: 'قانوني' },
  'asset.checkout.payment': { EN: 'Payment', AR: 'الدفع' },
  'asset.checkout.verify': { EN: 'Verify your Identity', AR: 'تحقق من هويتك' },
  'asset.checkout.verifyDesc': { EN: 'To comply with ADGM financial regulations, we need to verify your identity before you can purchase fractional shares.', AR: 'للامتثال للوائح المالية لسوق أبوظبي العالمي، نحتاج إلى التحقق من هويتك قبل أن تتمكن من شراء حصص جزئية.' },
  'asset.checkout.upload': { EN: 'Upload Government ID', AR: 'تحميل الهوية الحكومية' },
  'asset.checkout.uploadDesc': { EN: "Passport, Emirates ID, or Driver's License", AR: 'جواز السفر، أو الهوية الإماراتية، أو رخصة القيادة' },
  'asset.checkout.selectFile': { EN: 'Select File', AR: 'اختر ملف' },
  'asset.checkout.secureData': { EN: 'Your data is securely encrypted and processed by our regulated KYC partner.', AR: 'يتم تشفير بياناتك بشكل آمن ومعالجتها من قبل شريكنا المعتمد للتحقق من الهوية.' },
  'asset.checkout.continueLegal': { EN: 'Continue to Legal', AR: 'متابعة للقانوني' },
  'asset.checkout.agreement': { EN: 'Operating Agreement', AR: 'اتفاقية التشغيل' },
  'asset.checkout.reviewSign': { EN: 'Review and sign the LLC membership agreement.', AR: 'راجع ووقع اتفاقية عضوية الشركة المحدودة المسؤولية.' },
  'asset.checkout.agree': { EN: 'I have read and agree to the Operating Agreement, and I electronically sign this document.', AR: 'لقد قرأت وأوافق على اتفاقية التشغيل، وأوقع إلكترونياً على هذا المستند.' },
  'asset.checkout.back': { EN: 'Back', AR: 'رجوع' },
  'asset.checkout.signContinue': { EN: 'Sign & Continue', AR: 'توقيع ومتابعة' },
  'asset.checkout.complete': { EN: 'Complete Purchase', AR: 'إتمام الشراء' },
  'asset.checkout.totalDue': { EN: 'Total Amount Due', AR: 'إجمالي المبلغ المستحق' },
  'asset.checkout.creditCard': { EN: 'Credit Card', AR: 'بطاقة ائتمان' },
  'asset.checkout.bankTransfer': { EN: 'Bank Wire Transfer', AR: 'تحويل بنكي' },
  'asset.checkout.success': { EN: 'Purchase Successful!', AR: 'تم الشراء بنجاح!' },
  'asset.checkout.successDesc': { EN: 'Your shares have been added to your Vault. Redirecting...', AR: 'تم إضافة حصصك إلى خزنتك. جاري إعادة التوجيه...' },
  'asset.checkout.applePay': { EN: 'Pay with Apple Pay', AR: 'الدفع بواسطة Apple Pay' },
  'asset.checkout.googlePay': { EN: 'Pay with Google Pay', AR: 'الدفع بواسطة Google Pay' },
  'asset.checkout.orCard': { EN: 'Or pay with card', AR: 'أو الدفع بالبطاقة' },
  'asset.checkout.pay': { EN: 'Pay', AR: 'دفع' },
  'asset.checkout.totalPrice': { EN: 'Total Price', AR: 'السعر الإجمالي' },
  'asset.notFound': { EN: 'Asset not found', AR: 'الأصل غير موجود' },
  'asset.return': { EN: 'Return to Assets', AR: 'العودة إلى الأصول' },
  'footer.follow': { EN: 'Follow Us', AR: 'تابعنا' },
  'footer.download': { EN: 'Download on the', AR: 'حمل من' },
  'footer.appStore': { EN: 'App Store', AR: 'متجر التطبيقات' },
  'footer.rights': { EN: 'All rights reserved.', AR: 'جميع الحقوق محفوظة.' },
  'asset.calculator.title': { EN: 'Investment Calculator', AR: 'حاسبة الاستثمار' },
  'asset.calculator.shares': { EN: 'Select Shares', AR: 'حدد الحصص' },
  'asset.calculator.days': { EN: 'Days per year', AR: 'أيام في السنة' },
  'asset.calculator.total': { EN: 'Total Investment', AR: 'إجمالي الاستثمار' },
  'asset.share': { EN: 'Share', AR: 'حصة' },
  'asset.shares': { EN: 'Shares', AR: 'حصص' },
  'asset.available': { EN: 'Available', AR: 'متاح' },
  'asset.soldOut': { EN: 'Sold Out', AR: 'مباع بالكامل' },
  'asset.acquire': { EN: 'Acquire Share', AR: 'احصل على حصة' },
  'asset.pricePerShare': { EN: 'Price per Share', AR: 'السعر لكل حصة' },
  'footer.tagline': { EN: 'Own More. Together', AR: 'امتلك أكثر. معاً' },
  'footer.terms': { EN: 'Terms', AR: 'الشروط' },
  'footer.privacy': { EN: 'Privacy', AR: 'الخصوصية' },
  'footer.contact': { EN: 'Contact', AR: 'اتصل بنا' },
  'home.faq.title': { EN: 'Frequently Asked Questions', AR: 'الأسئلة الشائعة' },
  'home.faq.subtitle': { EN: 'Everything you need to know about fractional ownership in the UAE.', AR: 'كل ما تحتاج لمعرفته حول الملكية الجزئية في الإمارات.' },
  'home.faq.1.q': { EN: 'What is fractional ownership?', AR: 'ما هي الملكية الجزئية؟' },
  'home.faq.1.a': { EN: "Fractional ownership is a method in which several unrelated parties can share in, and mitigate the risk of, ownership of a high-value tangible asset. In Coshare's case, this includes supercars and yachts.", AR: 'الملكية الجزئية هي طريقة يمكن من خلالها لعدة أطراف غير مرتبطة المشاركة في ملكية أصل ملموس عالي القيمة وتخفيف مخاطرها. في حالة Coshare، يشمل ذلك السيارات الخارقة واليخوت.' },
  'home.faq.2.q': { EN: 'Is it legal in the UAE?', AR: 'هل هي قانونية في الإمارات؟' },
  'home.faq.2.a': { EN: 'Yes. Phase 1 utilizes a streamlined legal structure where legal title and registration (Mulkiya) are held by a vetted Lead Owner, with all other participants registered as authorized Cosharers (Named Drivers) to ensure strict RTA compliance.', AR: 'نعم. تستخدم المرحلة الأولى هيكلاً قانونياً مبسطاً حيث يحتفظ مالك رئيسي معتمد بالملكية القانونية والتسجيل (الملكية)، مع تسجيل جميع المشاركين الآخرين كمشاركين مفوضين (سائقين مسميين) لضمان الامتثال الصارم لهيئة الطرق والمواصلات.' },
  'home.faq.3.q': { EN: 'How are maintenance and insurance handled?', AR: 'كيف يتم التعامل مع الصيانة والتأمين؟' },
  'home.faq.3.a': { EN: 'Coshare provides a fully managed service. We handle all maintenance, comprehensive insurance, secure storage, and cleaning. Owners simply pay a proportional monthly management fee.', AR: 'توفر Coshare خدمة مدارة بالكامل. نحن نتولى جميع أعمال الصيانة والتأمين الشامل والتخزين الآمن والتنظيف. يدفع المالكون ببساطة رسوم إدارة شهرية تناسبية.' },
  'home.faq.4.q': { EN: 'Can I sell my fraction later?', AR: 'هل يمكنني بيع حصتي لاحقاً؟' },
  'home.faq.4.a': { EN: 'Yes. Coshare provides a secondary marketplace where you can list your shares for sale to other verified users, providing liquidity to your luxury investments.', AR: 'نعم. توفر Coshare سوقاً ثانوياً حيث يمكنك عرض حصصك للبيع لمستخدمين آخرين تم التحقق منهم، مما يوفر السيولة لاستثماراتك الفاخرة.' },
  'home.faq.5.q': { EN: 'How do I book time with the asset?', AR: 'كيف يمكنني حجز وقت لاستخدام الأصل؟' },
  'home.faq.5.a': { EN: 'You can book time through the Coshare app. Our AI-powered calendar ensures fair distribution of peak and off-peak days based on your share percentage.', AR: 'يمكنك حجز الوقت من خلال تطبيق Coshare. يضمن تقويمنا المدعوم بالذكاء الاصطناعي التوزيع العادل لأيام الذروة والأيام العادية بناءً على نسبة حصتك.' },
  'home.faq.6.q': { EN: 'What happens if an asset is damaged?', AR: 'ماذا يحدث إذا تعرض الأصل للتلف؟' },
  'home.faq.6.a': { EN: 'All assets are fully comprehensively insured. In the event of damage, the insurance covers the repair costs, and our management team handles the entire process.', AR: 'جميع الأصول مؤمنة تأميناً شاملاً بالكامل. في حالة حدوث تلف، يغطي التأمين تكاليف الإصلاح، ويتولى فريق الإدارة لدينا العملية بأكملها.' },
  'home.faq.7.q': { EN: 'Are there any hidden fees?', AR: 'هل هناك أي رسوم خفية؟' },
  'home.faq.7.a': { EN: 'No. We believe in complete transparency. You pay the initial share price and a fixed monthly management fee that covers all operational costs.', AR: 'لا. نحن نؤمن بالشفافية التامة. أنت تدفع سعر الحصة الأولي ورسوم إدارة شهرية ثابتة تغطي جميع التكاليف التشغيلية.' },
  'home.faq.8.q': { EN: 'Who can use the asset?', AR: 'من يمكنه استخدام الأصل؟' },
  'home.faq.8.a': { EN: 'Only verified co-owners who have passed our strict KYC and background checks are authorized to use the asset.', AR: 'فقط الملاك المشاركون الذين تم التحقق منهم واجتازوا فحوصات "اعرف عميلك" والخلفية الصارمة الخاصة بنا مصرح لهم باستخدام الأصل.' },
  'asset.legal.title': { EN: 'Legal & Ownership Structure', AR: 'الهيكل القانوني والملكية' },
  'asset.legal.desc': { EN: 'Phase 1 utilizes a streamlined legal structure where legal title and registration (Mulkiya) are held by a vetted Lead Owner, with all other participants registered as authorized Cosharers (Named Drivers) to ensure strict RTA compliance.', AR: 'تستخدم المرحلة الأولى هيكلاً قانونياً مبسطاً حيث يحتفظ مالك رئيسي معتمد بالملكية القانونية والتسجيل (الملكية)، مع تسجيل جميع المشاركين الآخرين كمشاركين مفوضين (سائقين مسميين) لضمان الامتثال الصارم لهيئة الطرق والمواصلات.' },
  'asset.legal.entityType': { EN: 'Entity Type', AR: 'نوع الكيان' },
  'asset.legal.entityValue': { EN: 'Lead Owner & Authorized Cosharers', AR: 'مالك رئيسي ومشاركون مفوضون' },
  'asset.legal.status': { EN: 'Asset Status', AR: 'حالة الأصل' },
  'asset.legal.statusValue': { EN: 'Fully Insured & RTA Compliant', AR: 'مؤمن بالكامل ومتوافق مع هيئة الطرق والمواصلات' },
  'asset.legal.docs': { EN: 'Due Diligence Documents', AR: 'وثائق العناية الواجبة' },
  'asset.legal.doc1': { EN: 'Cosharing Agreement (Draft)', AR: 'اتفاقية المشاركة (مسودة)' },
  'asset.legal.doc2': { EN: 'Independent Valuation Report', AR: 'تقرير تقييم مستقل' },
  'asset.legal.doc3': { EN: 'Physical Inspection Certificate', AR: 'شهادة فحص فيزيائي' },
  'asset.benefits.title': { EN: 'Ownership Benefits', AR: 'مزايا الملكية' },
  'asset.benefits.usage': { EN: 'Guaranteed Usage Days', AR: 'أيام استخدام مضمونة' },
  'asset.benefits.usageDesc': { EN: 'Enjoy proportional access to the asset throughout the year based on your share ownership.', AR: 'استمتع بوصول تناسبي للأصل طوال العام بناءً على ملكيتك للحصص.' },
  'asset.benefits.managed': { EN: 'Fully Managed', AR: 'مدار بالكامل' },
  'asset.benefits.managedDesc': { EN: 'Maintenance, insurance, and storage are completely handled by the coshare. team.', AR: 'يتم التعامل مع الصيانة والتأمين والتخزين بالكامل من قبل فريق coshare.' },
  'dashboard.title': { EN: 'The Vault', AR: 'الخزنة' },
  'dashboard.subtitle': { EN: 'Your exclusive co-owner portfolio and asset management dashboard.', AR: 'محفظتك الحصرية للملكية المشتركة ولوحة تحكم إدارة الأصول.' },
  'dashboard.tabs.holdings': { EN: 'Holdings', AR: 'الممتلكات' },
  'dashboard.tabs.analytics': { EN: 'Analytics', AR: 'التحليلات' },
  'dashboard.tabs.marketplace': { EN: 'Sell Requests', AR: 'طلبات البيع' },
  'dashboard.stats.equity': { EN: 'Total Equity Value', AR: 'إجمالي قيمة الملكية' },
  'dashboard.stats.assets': { EN: 'Assets Owned', AR: 'الأصول المملوكة' },
  'dashboard.stats.yield': { EN: 'Est. Appreciation', AR: 'التقدير المتوقع' },
  'dashboard.holdings.title': { EN: 'Your Holdings', AR: 'ممتلكاتك' },
  'dashboard.holdings.empty': { EN: "You don't own any assets yet.", AR: 'لا تملك أي أصول بعد.' },
  'dashboard.holdings.explore': { EN: 'Explore Assets', AR: 'استكشف الأصول' },
  'dashboard.holdings.book': { EN: 'Book', AR: 'حجز' },
  'dashboard.analytics.growth': { EN: 'Portfolio Growth', AR: 'نمو المحفظة' },
  'dashboard.analytics.allocation': { EN: 'Asset Allocation', AR: 'توزيع الأصول' },
  'dashboard.insight.title': { EN: 'Vault Insight: High Growth Opportunity', AR: 'رؤية الخزنة: فرصة نمو مرتفع' },
  'dashboard.marketplace.title': { EN: 'Sell Requests', AR: 'طلبات البيع' },
  'dashboard.marketplace.empty': { EN: 'No active sell requests.', AR: 'لا توجد طلبات بيع نشطة.' },
  'dashboard.accessDenied': { EN: 'Access Denied', AR: 'تم رفض الوصول' },
  'dashboard.signInToView': { EN: 'Please sign in to view your Vault.', AR: 'يرجى تسجيل الدخول لعرض خزنتك.' },
  'dashboard.stats.estAnnual': { EN: 'Est. Annual', AR: 'تقديري سنوي' },
  'dashboard.holdings.equityValue': { EN: 'Equity Value', AR: 'قيمة الملكية' },
  'dashboard.holdings.listResale': { EN: 'List for Resale', AR: 'اعرض لإعادة البيع' },
  'dashboard.analytics.growthDesc': { EN: 'Historical equity value performance', AR: 'أداء قيمة الملكية التاريخي' },
  'dashboard.analytics.equity': { EN: 'Equity', AR: 'الملكية' },
  'dashboard.analytics.allocationDesc': { EN: 'Distribution by category', AR: 'التوزيع حسب الفئة' },
  'dashboard.insight.desc': { EN: 'Your current portfolio is heavily weighted in Supercars. Based on market trends in Dubai, diversifying into Yachts could increase your overall projected appreciation by 2.4% annually.', AR: 'محفظتك الحالية مثقلة بالسيارات الخارقة. بناءً على اتجاهات السوق في دبي، قد يؤدي التنويع في اليخوت إلى زيادة تقديرك الإجمالي المتوقع بنسبة 2.4٪ سنوياً.' },
  'dashboard.insight.cta': { EN: 'View Recommendations', AR: 'عرض التوصيات' },
  'dashboard.marketplace.subtitle': { EN: 'Submit a request to sell your shares back to coshare. or other members.', AR: 'أرسل طلبًا لبيع حصصك إلى coshare. أو الأعضاء الآخرين.' },
  'dashboard.marketplace.fee': { EN: 'Admin Review Required', AR: 'مطلوب مراجعة الإدارة' },
  'dashboard.marketplace.firstListing': { EN: 'You have no pending sell requests.', AR: 'ليس لديك طلبات بيع معلقة.' },
  'dashboard.marketplace.yourListing': { EN: 'Pending Request', AR: 'طلب معلق' },
  'dashboard.marketplace.cancel': { EN: 'Cancel Request', AR: 'إلغاء الطلب' },
  'dashboard.marketplace.buy': { EN: 'Buy Shares', AR: 'شراء حصص' },
  'dashboard.resale.title': { EN: 'Request to Sell', AR: 'طلب بيع' },
  'dashboard.resale.subtitle': { EN: 'Sell Request', AR: 'طلب بيع' },
  'dashboard.resale.sharesOwned': { EN: 'Shares Owned', AR: 'الحصص المملوكة' },
  'dashboard.resale.numToSell': { EN: 'Number of Shares to Sell', AR: 'عدد الحصص للبيع' },
  'dashboard.resale.pricePerShare': { EN: 'Desired Price per Share (AED)', AR: 'السعر المطلوب لكل حصة (درهم)' },
  'dashboard.resale.recommended': { EN: 'Recommended price', AR: 'السعر الموصى به' },
  'dashboard.resale.totalValue': { EN: 'Total Request Value', AR: 'إجمالي قيمة الطلب' },
  'dashboard.resale.serviceFee': { EN: 'Est. Service Fee (2.5%)', AR: 'رسوم الخدمة التقديرية (2.5٪)' },
  'dashboard.resale.confirm': { EN: 'Submit Request', AR: 'إرسال الطلب' },
  'dashboard.resale.seller': { EN: 'Seller', AR: 'البائع' },
  'dashboard.categories.supercars': { EN: 'Supercars', AR: 'سيارات خارقة' },
  'dashboard.categories.yachts': { EN: 'Yachts', AR: 'يخوت' },
  'vault.shares': { EN: 'Shares', AR: 'حصص' },
  'vault.dispute.file': { EN: 'File Dispute', AR: 'تقديم نزاع' },
  'vault.tabs.overview': { EN: 'Overview', AR: 'نظرة عامة' },
  'vault.tabs.documents': { EN: 'Documents', AR: 'المستندات' },
  'vault.tabs.maintenance': { EN: 'Maintenance', AR: 'الصيانة' },
  'vault.tabs.inspections': { EN: 'Inspections', AR: 'الفحوصات' },
  'vault.tabs.voting': { EN: 'Voting', AR: 'التصويت' },
  'vault.tabs.chat': { EN: 'Co-owner Chat', AR: 'دردشة الملاك' },
  'vault.overview.purchaseDate': { EN: 'Purchase Date', AR: 'تاريخ الشراء' },
  'vault.overview.specs': { EN: 'Asset Specifications', AR: 'مواصفات الأصل' },
  'vault.chat.report': { EN: 'Report Violation', AR: 'إبلاغ عن مخالفة' },
  'vault.chat.empty': { EN: 'Start a conversation with other co-owners.', AR: 'ابدأ محادثة مع الملاك المشاركين الآخرين.' },
  'vault.chat.placeholder': { EN: 'Type a message...', AR: 'اكتب رسالة...' },
  'vault.dispute.title': { EN: 'File a Dispute', AR: 'تقديم نزاع' },
  'vault.dispute.subtitle': { EN: 'Report a co-owner violation', AR: 'الإبلاغ عن مخالفة مالك مشارك' },
  'vault.dispute.success.title': { EN: 'Dispute Submitted', AR: 'تم تقديم النزاع' },
  'vault.dispute.success.desc': { EN: 'Our team will review the report and take appropriate action.', AR: 'سيقوم فريقنا بمراجعة التقرير واتخاذ الإجراء المناسب.' },
  'vault.dispute.reason.label': { EN: 'Reason', AR: 'السبب' },
  'vault.dispute.reason.placeholder': { EN: 'Select a reason', AR: 'اختر سبباً' },
  'vault.dispute.reason.damage': { EN: 'Asset Damage', AR: 'تلف الأصل' },
  'vault.dispute.reason.late': { EN: 'Late Return', AR: 'تأخر في العودة' },
  'vault.dispute.reason.violation': { EN: 'Rules Violation', AR: 'مخالفة القواعد' },
  'vault.dispute.reason.cleanliness': { EN: 'Cleanliness Issues', AR: 'مشاكل النظافة' },
  'vault.dispute.reason.other': { EN: 'Other', AR: 'أخرى' },
  'vault.dispute.desc.label': { EN: 'Description', AR: 'الوصف' },
  'vault.dispute.desc.placeholder': { EN: 'Please provide details about the violation...', AR: 'يرجى تقديم تفاصيل حول المخالفة...' },
  'vault.dispute.submit': { EN: 'Submit Report', AR: 'إرسال التقرير' },
  'vault.status.completed': { EN: 'Completed', AR: 'مكتمل' },
  'vault.status.upcoming': { EN: 'Upcoming', AR: 'قادم' },
  'vault.status.passed': { EN: 'Passed', AR: 'ناجح' },
  'vault.specs.engine': { EN: 'Engine', AR: 'المحرك' },
  'vault.specs.topSpeed': { EN: 'Top Speed', AR: 'السرعة القصوى' },
  'vault.specs.acceleration': { EN: 'Acceleration', AR: 'التسارع' },
  'vault.specs.length': { EN: 'Length', AR: 'الطول' },
  'vault.specs.guests': { EN: 'Guests', AR: 'الضيوف' },
  'vault.specs.cabins': { EN: 'Cabins', AR: 'الكبائن' },
  'login.title': { EN: 'Sign in to', AR: 'تسجيل الدخول إلى' },
  'login.subtitle': { EN: 'Access your premium fractional assets', AR: 'الوصول إلى أصولك الجزئية المتميزة' },
  'login.back': { EN: 'Back to Home', AR: 'العودة للرئيسية' },
  'login.google': { EN: 'Continue with Google', AR: 'المتابعة باستخدام جوجل' },
  'login.apple': { EN: 'Continue with Apple', AR: 'المتابعة باستخدام أبل' },
  'login.phone': { EN: 'Continue with Phone', AR: 'المتابعة باستخدام الهاتف' },
  'login.or': { EN: 'or', AR: 'أو' },
  'login.demo': { EN: 'Explore with Demo Account', AR: 'استكشف بحساب تجريبي' },
  'login.terms': { EN: 'By signing in, you agree to our', AR: 'بتسجيل الدخول، فإنك توافق على' },
  'login.tos': { EN: 'Terms of Service', AR: 'شروط الخدمة' },
  'login.privacy': { EN: 'Privacy Policy', AR: 'سياسة الخصوصية' },
  'login.comingSoon': { EN: 'coming soon!', AR: 'قريباً!' },
  'month.oct': { EN: 'Oct', AR: 'أكتوبر' },
  'month.nov': { EN: 'Nov', AR: 'نوفمبر' },
  'month.dec': { EN: 'Dec', AR: 'ديسمبر' },
  'month.jan': { EN: 'Jan', AR: 'يناير' },
  'month.feb': { EN: 'Feb', AR: 'فبراير' },
  'month.mar': { EN: 'Mar', AR: 'مارس' },
  'seo.dashboard.title': { EN: 'Dashboard | Coshare Portfolio', AR: 'لوحة التحكم | محفظة Coshare' },
  'seo.dashboard.desc': { EN: 'Manage your fractional ownership portfolio, track asset performance, and trade shares on the Coshare marketplace.', AR: 'إدارة محفظة الملكية الجزئية الخاصة بك، وتتبع أداء الأصول، وتداول الحصص في سوق Coshare.' },
  'seo.assets.title': { EN: 'Browse Assets | Coshare Fractional Ownership', AR: 'تصفح الأصول | الملكية الجزئية من Coshare' },
  'seo.assets.desc': { EN: 'Explore our curated collection of luxury supercars, yachts, and desert 4x4s available for fractional ownership in the UAE.', AR: 'استكشف مجموعتنا المختارة من السيارات الخارقة واليخوت وسيارات الدفع الرباعي الصحراوية المتاحة للملكية الجزئية في الإمارات.' },
  'asset.notFound.title': { EN: 'Asset not found', AR: 'الأصل غير موجود' },
  'asset.notFound.return': { EN: 'Return to Assets', AR: 'العودة إلى الأصول' },
};

interface LanguageContextType {
  lang: Language;
  toggleLang: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>(() => {
    const saved = localStorage.getItem('coshare_lang');
    return (saved === 'AR' || saved === 'EN') ? saved : 'EN';
  });

  useEffect(() => {
    document.documentElement.dir = lang === 'AR' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang.toLowerCase();
    localStorage.setItem('coshare_lang', lang);
  }, [lang]);

  const toggleLang = () => {
    setLang((prev) => (prev === 'EN' ? 'AR' : 'EN'));
  };

  const t = (key: string): string => {
    if (translations[key]) {
      return translations[key][lang];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
